name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # Specify the path to your Dockerfile if it's not in the root
          push: true
          tags: |
            ghcr.io/stephenjoly/landing-page/stephenjoly-resume-site:latest
            ghcr.io/stephenjoly/landing-page/stephenjoly-resume-site:${{ github.sha }}