name: Build and Publish Docker Image

on:
  push:
    branches:
      - main # Replace with your main branch name if different

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u stephenjoly --password-stdin

      - name: Build and push Docker image
        env:
          REPO_OWNER: stephenjoly
          REPO_NAME: landing-page
          IMAGE_NAME: stephenjoly-resume-site
          IMAGE_TAG: latest
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${REPO_OWNER}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG} \
            --push .

      - name: Build and push Docker image with commit SHA
        env:
          REPO_OWNER: stephenjoly
          REPO_NAME: landing-page
          IMAGE_NAME: stephenjoly-resume-site
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${REPO_OWNER}/${REPO_NAME}/${IMAGE_NAME}:${IMAGE_TAG} \
            --push .
